### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by fphammerle** [fphammerle/tooncher#2]
```python
Traceback (most recent call last):
  File "$HOME/.local/bin/tooncher", line 11, in <module>
    sys.exit(main())
  File "$HOME/.local/lib/python3.6/site-packages/tooncher/_cli.py", line 112, in main
    run(**vars(args))
  File "$HOME/.local/lib/python3.6/site-packages/tooncher/_cli.py", line 56, in run
    cpu_limit_percent=cpu_limit_percent,
  File "$HOME/.local/lib/python3.6/site-packages/tooncher/__init__.py", line 105, in launch
    username=username, password=password, validate_ssl_cert=validate_ssl_certs,
  File "$HOME/.local/lib/python3.6/site-packages/tooncher/__init__.py", line 86, in _login
    url=_LOGIN_API_URL, params=req_params, validate_ssl_cert=validate_ssl_cert,
  File "$HOME/.local/lib/python3.6/site-packages/tooncher/__init__.py", line 51, in _api_request
    context=None if validate_ssl_cert else ssl._create_unverified_context(),
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by fphammerle** [comment]
test via
```
curl https://www.toontownrewritten.com/api/login?format=json --data-urlencode username=myuser --data-urlencode "password=secret"
```

**Comment by fphammerle** [comment]
response body: `b'error code: 1010'`

**Comment by fphammerle** [comment]
```
Error 1010 Ray ID: *** • 2020-05-05 16:39:33 UTC
Access denied
What happened?
The owner of this website (www.toontownrewritten.com) has banned your access based on your browser's signature ( ***).

Cloudflare Ray ID: *** • Your IP:  *** • Performance & security by Cloudflare
```

**Comment by fphammerle** [comment]
fixed in https://github.com/fphammerle/tooncher/releases/tag/1.0.2
